/**
 *
 * Jose Lugo-Martinez, jlugomar@indiana.edu
 * School of Informatics and Computing
 * Indiana University-Bloomington 
 *
 * Aug-6-2012
 *
 * Copyright (c) 2014 Jose Lugo-Martinez,
 * Vladimir Vacic, and Predrag Radivojac.
 *
 */

#ifndef __CONFIG_H__
#define __CONFIG_H__

#define GRAPHLET_SIZE  4 
#define GRAPHLET_TYPES 74       // Maximum number of n-graphlets up to n=5.
#define GRAPHLET_TYPES_SIZE 127 // Unused  
#define LOG_GRAPHLET_TYPES_SIZE 7 
#define ALPHABET_SIZE 31
#define LOG_ALPHABET_SIZE 5
#define ZERO_CHAR '@'
#define SIMILARITY_THRESHOLD 1.0

// Flags for setting desired graphlet combination.
#define GRAPHLETS_1 1 // If 1 use 1-graphlets when counting, otherwise do not consider 1-graphlets.
#define GRAPHLETS_2 1 // If 1 use 2-graphlets when counting, otherwise do not consider 2-graphlets.
#define GRAPHLETS_3 1 // If 1 use 3-graphlets when counting, otherwise do not consider 3-graphlets.
#define GRAPHLETS_4 1 // If 1 use 4-graphlets when counting, otherwise do not consider 4-graphlets.
#define GRAPHLETS_5 0 // If 1 use 5-graphlets when counting, otherwise do not consider 5-graphlets.

#define OUTPUT_FORMAT 2 // If 0 print kernel matrix in binary format (for efficient SVM^light), 
                        // If 1 print triangular kernel matrix to standard output, 
                        // Otherwise, print to standard output.

#include <fstream>
#include <utility>
#include <list>
#include <map>
#include <vector>
using namespace std;


typedef unsigned long Key;


// Enhanced data structure to accommodate for label and edge mismatches.
struct MismatchInfo
{
    float matches;						// Contains counts for exact non-isomorphic labeled graphlets found.
    float mismatches;					// Contains counts for inexact non-isomorphic labeled graphlets obtained by edge indels algorithm.
    map<Key, float> mismatchesGraph;	// Contains counts for each inexact non-isomorphic labeled graphlet generated by label substitutions algorithm and satisfying SIMILARITY_THRESHOLD (defined above).
};

#endif

